### ISSUE TITLE
Thank you for making this available

### ISSUE THREAD

**Issue by SimonBiggs** [anthonytec2/xrayscanner#3]
Hi Anthony,

Thank you for going to the effort to make this available.

I am currently in the process of gathering resources to create a collapsed cone algorithm (https://link.springer.com/article/10.3938/jkps.61.2073). Potentially the work you've done here could be a great help for a particular component of that.

Discussions about work on that (which is minimal at the moment) is at https://groups.google.com/forum/#!topic/python-medphys/bFPshVTS8gs

Thank you again.
Cheers,
Simon

**Comment by anthonytec2** [comment]
Any time. Do let me know if you need any help with integrating this or need any further help with the development of the algorithm. I would be happy to do either!

**Comment by SimonBiggs** [comment]
That sounds great. I've just sent an email.
